### ISSUE TITLE
Launch error / inconsistent files

### ISSUE THREAD

**Issue by viiuan** [Tre5et/treelauncher#5] opened 2024-05-04 03:09 UTC
I was trying out version 20w14∞ for fun in a new instance, but upon exiting the game it never stopped cleaning up game files and I had to force close the launcher. It has resulted in inconsistent files which were unabled to be repaired automatically and attempting to launch the instance again gives this error.
![image](https://github.com/Tre5et/treelauncher/assets/63260365/7c3c0f98-d12b-409e-8803-caf0f88d5267)
How can I rectify this on my end for now? I was planning on reopening the instance to delete my saves and then delete the instance anyway.
Edit: Tried deleting the 20w14∞ instance to see if that would do anything but now I get an error for that too.
Edit 2: Since I am impatient I just backed up my data and reinstalled the launcher for now. I wonder if this is reproduceable...

**Comment by Tre5et** [comment] 2024-05-04 10:55
This doesn't seem great. Can you send me the logs both of when this happened and when you tried to repair the files? I can try to figure out what went wrong and how to fix it using them. They are found in the folder 'logs' in the install directory (default: C:/user/[name]/AppData/local/TreeLauncher).

**Comment by viiuan** [comment] 2024-05-04 15:24
I am so sorry, it looks like I lost the original log in the reinstall and that folder was not part of my backup (I only backed up treelauncher-data). Attempting to reproduce yielded nothing. If something like this happens again I will ensure I save that log somewhere safe... and hopefully this was something very rare. Sorry again, I feel like a real dummy for not having backed that up now.

**Comment by viiuan** [comment] 2024-05-04 16:35
The endless cleaning up game files happened again, but in a different situation, not sure why it's happening. This happened after I went to continue in a world of mine and for some reason all saves gave the experimental settings warning (edit: this was likely because I forgot to disable the Dimensional Doors mod). Here are the logs before and after I force closed the launcher.
The issue that is given is that it's unable to clean up game files.
[current.log](https://github.com/Tre5et/treelauncher/files/15210374/current.log)
[current.log](https://github.com/Tre5et/treelauncher/files/15210375/current.log)

EDIT: Closing and reopening the launcher normally apparently reconbobulated something, and the launcher was able to automatically restore.
EDIT 2: It's now getting stuck in this loop whenever I close my game and I keep getting the error of being unable to clean up game data... really weird.
[current.log](https://github.com/Tre5et/treelauncher/files/15210389/current.log)

**Comment by Tre5et** [comment] 2024-05-05 08:00
From #8:
[2024-05-04_2.log.gz](https://github.com/Tre5et/treelauncher/files/15211657/2024-05-04_2.log.gz)

**Comment by Tre5et** [comment] 2024-05-05 08:13
It seems, that the launcher is not able to move your saves to the correct location that is required because of the way it works.

I have tracked down an issue that must be contributing to the strange behavior, though it shouldn't be causing it by itself.

Did you have your saves folder open while the game was trying to close? If so, Windows is _sometimes_  
 doesn't let programs modify the contents of this folder. This is really something the launcher should detect and give a warning about, though. I'll work out a way to do this.

**Comment by viiuan** [comment] 2024-05-05 15:57
I can't be sure as I have sometimes had the file system open (not necessarily on the saves folder) while playing but other times I have not. For now I can ensure that my Explorer stays closed while I'm exiting the game, but if it happens otherwise I'll post another log!
I wonder if it could also be antivirus related though I just have good ol' Windows Defender and I'm not sure just how disruptive that could be on its own. Worst-case scenario I could always add TreeLauncher's folders as exceptions and see if that helps.

**Comment by Tre5et** [comment] 2024-05-05 19:19
I have implemented a fix in v2.2.4, which at least should prevent the launcher from getting stuck on the cleanup screen.

I'm pretty sure these issues are caused by the operating system preventing the launcher from modifying the game files for whatever reason. Unfortunately, it doesn't seem like I can do much about that. There now is a message telling the user that this happened and allowing a retry.

I'm closing the issue for now, but if you have any further problems or ideas when exactly this happens, feel free to comment again.

**Closed as completed by Tre5et** 2024-05-05 19:19 UTC
